spring:
  application:
    name: members-be
    version: 1.0
  datasource:
    url: jdbc:postgresql://localhost:5432/members
    username: postgres
    password: MorIng820401
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
    open-in-view: false
  security:
    user:
      name: admin
      password: secretpassword
      roles: ADMIN